# Use the official Nginx image as the base image
FROM nginx:1.21

# Copy the HTML files and Nginx configuration to the container
# COPY dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to allow incoming traffic
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]